"""add unique constraint to many to many link tables

Revision ID: 31f6fc56c901
Revises: b2b9fa187414
Create Date: 2023-07-24 00:10:52.271772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f6fc56c901'
down_revision = 'b2b9fa187414'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_posts_digests', 'post_digests', ['post_id', 'digest_id'])
    op.alter_column('posts', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint('uq_posts_tags', 'posts_tags', ['post_id', 'tag_id'])
    op.create_unique_constraint('uq_subscriptions_tags', 'subscriptions_tags', ['subscription_id', 'tag_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subscriptions_tags', 'subscriptions_tags', type_='unique')
    op.drop_constraint('uq_posts_tags', 'posts_tags', type_='unique')
    op.alter_column('posts', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('uq_posts_digests', 'post_digests', type_='unique')
    # ### end Alembic commands ###
