"""remove unique from post text

Revision ID: 6af0ceec2102
Revises: 23b1a9aa48aa
Create Date: 2023-07-23 00:29:35.335494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6af0ceec2102'
down_revision = '23b1a9aa48aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('digests', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('posts', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('posts_text_key', 'posts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('posts_text_key', 'posts', ['text'])
    op.alter_column('posts', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('digests', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
