"""add created fields

Revision ID: 82b3ee52fd5d
Revises: ee9f1142c89d
Create Date: 2023-07-22 20:28:24.766542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b3ee52fd5d'
down_revision = 'ee9f1142c89d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digests', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('posts', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'created')
    op.drop_column('digests', 'created')
    # ### end Alembic commands ###
