"""add unique together to Subscription

Revision ID: b2b9fa187414
Revises: 7564686032c4
Create Date: 2023-07-23 13:58:21.450778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b9fa187414'
down_revision = '7564686032c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_source', 'subscriptions', ['user_id', 'source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_source', 'subscriptions', type_='unique')
    # ### end Alembic commands ###
