"""change default value in created

Revision ID: b9e1219f2c12
Revises: 39203dc13bba
Create Date: 2023-07-23 00:57:11.949049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e1219f2c12'
down_revision = '39203dc13bba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
